# Generated by Django 4.1.7 on 2023-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=50)),
                ('experiance', models.CharField(default='', max_length=10)),
                ('qualification', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('website', models.URLField(default='')),
                ('company_logo', models.ImageField(default='', upload_to='company_logo')),
                ('company_address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
