# Generated by Django 4.1.7 on 2023-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
